questionsBike = {
	{ "Caddenin hangi tarafında sürmelisiniz?", "Sol", "Sağ", "Herhangi biri", 2 },
	{ "Koruyucu ekipman (örn: kask) takmanın amacı nedir?", "Havalı görünmek", "Korunmak", "Dikkat çekmek", 2 },
	{ "Kamyonların sizi göremeyeceği kör noktalar:", "Doğrudan arkasında", "Kabinin hemen solunda", "Hepsi", 3 },
	{ "UYMAK ZORUNDA olduğunuz uyarı tabelalarının rengi genelde nedir?", "Yeşil", "Mavi", "Kırmızı", 3 },
	{ "Motor hacmi şu değerin altındaysa otoyola motosikletle çıkmak yasaktır:", "50cc", "125cc", "250cc", 1 },
	{
		"Aynı yönde giden birden fazla şerit varsa, sürücü nerede gitmeli?",
		"Herhangi bir şeritte",
		"Sol şeritte",
		"Geçiş haricinde sağ şeritte",
		3,
	},
	{
		"Keskin virajlara yavaşça yaklaşma nedeniniz ne olabilir?",
		"Lastiklerin aşınmasını azaltmak için",
		"Manzaranın tadını çıkarmak için",
		"Yolda biri varsa durabilmek için",
		3,
	},
	{
		"Kask neden tasarlanmıştır?",
		"Üzerine havalı mohawk yapıştırmak için",
		"Polisten yüzümü gizlemek için",
		"Kafamı korumak için",
		3,
	},
	{
		"Bir aracı takip ederken acil duruma karşı ne kadar mesafe bırakmalısınız?",
		"10 ft",
		"15 ft",
		"20 ft",
		2,
	},
	{ "Aşağıdaki motor hacminde ehliyet gerekmez:", "50cc", "125cc", "250cc", 1 },
}

questionsBoat = {
	{
		"Bir teknede bulunması gereken şey nedir?",
		"Güvenlik ekipmanları",
		"Tavuklu sandviç",
		"Balıkçılık malzemeleri",
		1,
	},
	{ "Tekneyi yanaştırırken ne yapmalısınız?", "Demir atmak", "Salın gitsin", "Arkaya yaslanıp izlemek", 1 },
	{ "Göller ve kanallarda hız limiti nedir?", "40 knot", "60 knot", "90 knot", 2 },
	{ "Açık denizde hız limiti nedir?", "60 knot", "90 knot", "Limit yok", 3 },
	{ "Aşağıdaki bölgelerden hangisinde ağ atmak yasaktır?", "Göller", "Kanal", "Açık deniz", 1 },
	{
		"Teknede bir sorun yaşarsanız kimi aramalısınız?",
		"911 - Deniz Polisi isteyin",
		"911 - Acil servis isteyin",
		"5555 - Wolf Claw Çekici",
		1,
	},
	{ "Tekneniz neyle tanımlanır?", "Rengiyle", "Marka ve modeliyle", "Adıyla", 3 },
	{ "Teknenizde bulunması gereken güvenlik ekipmanı miktarı nedir?", "3", "Kişi başına 1", "8", 2 },
	{
		"Deniz Polisi telsizle sizinle iletişime geçerse ne yapmalısınız?",
		"Cevap verip emirlerine uymalısınız",
		"Kaçın",
		"Yok sayın",
		1,
	},
	{ "Tekneniz sadece şuralara park edilebilir:", "Plaja bağlı olarak", "Okyanusun ortasında", "Bir iskeleye", 3 },
}

questionsCar = {
	{ "Caddenin hangi tarafında sürmelisiniz?", "Sol", "Sağ", "Herhangi biri", 2 },
	{
		"Dört yönlü duraklı bir kavşakta, ilk kim geçebilir?",
		"Sizin solunuzdaki sürücü",
		"Sizin sağınızdaki sürücü",
		"Kavşağa ilk gelen",
		2,
	},
	{
		"Keskin viraja yavaşça yaklaşma nedeniniz ne olabilir?",
		"Lastiklerin aşınmasını azaltmak için",
		"Manzaranın tadını çıkarmak için",
		"Yolda biri varsa durabilmek için",
		3,
	},
	{
		"Trafik ışığı kırmızı olduğunda ne yapmalısınız?",
		"Aracı tamamen durdurun",
		"Devam edin",
		"Bir şey gelmiyorsa geçin",
		1,
	},
	{ "Sürücüler yayalara ne zaman yol vermelidir?", "Her zaman", "Özel mülkte", "Sadece yaya geçidinde", 1 },
	{ "Kamyonların sizi göremeyeceği kör noktalar:", "Doğrudan arkasında", "Kabinin hemen solunda", "Hepsi", 3 },
	{
		"Arkanızdan sirenli bir acil araç gelirse ne yapmalısınız?",
		"Yavaşlayıp devam edin",
		"Sağa çekip durun",
		"Hızınızı koruyun",
		2,
	},
	{
		"Aynı yönde giden birden fazla şerit varsa, sürücü nerede gitmeli?",
		"Herhangi bir şeritte",
		"Sol şeritte",
		"Geçiş haricinde sağ şeritte",
		3,
	},
	{
		"Kötü hava koşullarında aracınızı daha görünür kılmak için ne yapmalısınız?",
		"Farları açın",
		"Dörtlüleri açın",
		"Uzun farları yakıp söndürün",
		1,
	},
	{ "Yangın musluğuna kaç feet yaklaşamazsınız?", "10 feet", "15 feet", "20 feet", 2 },
}
