addEvent("global.playSound3D", true)
addEventHandler("global.playSound3D", root, function(soundPath, looped, distance, volume, throttled)
	local x, y, z = getElementPosition(source)
	local sound = playSound3D(soundPath, x, y, z, looped, throttled)
	attachElements(sound, source)
	setSoundMaxDistance(sound, distance)
	getSoundVolume(sound, volume)
	setElementInterior(sound, getElementInterior(source))
	setElementDimension(sound, getElementDimension(source))
end)
