handlingValues = {
	{ "Maksimum Hız (Km/h)", 0.1, 600, ref = "maxVelocity" },
	{ "Hızlanma", 0.1, 100, ref = "engineAcceleration" },
	{ "Motor Gücü", 0.1, 100, ref = "engineInertia" },

	{ "Süspansiyon Yüksekliği", -5, 0.2, ref = "suspensionLowerLimit" },
	{ "Süspansiyon Eğilimi", 0.05, 0.95, ref = "suspensionFrontRearBias" },
	{ "Süspansiyon Seviyesi", 0.01, 3, ref = "suspensionForceLevel" },
	{ "Süspansiyon Damping", 0.01, 0.2, ref = "suspensionDamping" },
	{ "Direksiyon Kilidi", 0.1, 55, ref = "steeringLock" },

	{ "Araç Ağırlığı (Kg)", 50, 10000, ref = "mass" },
	{ "Ağırlık Merkezi X", -1, 1, ref = "centerOfMassX" },
	{ "Ağırlık Merkezi Y", -1, 1, ref = "centerOfMassY" },
	{ "Ağırlık Merkezi Z", -1, 1, ref = "centerOfMassZ" },

	{ "Drag Coefficiency", 0.1, 6, ref = "dragCoeff" },
	{ "Fren Gücü", 0.1, 50, ref = "brakeDeceleration" },
	{ "Fren Eğilimi", 0.1, 1, ref = "brakeBias" },
	{ "Çekiş Çarpanı", 0.1, 6, ref = "tractionMultiplier" },
	{ "Çekiş Eğilimi", 0.1, 1, ref = "tractionBias" },
}

handlings = {
	[1] = { "mass", mass },
	[2] = { "turnMass", turnMass },
	[3] = { "dragCoeff", dragCoeff },
	[4] = { "centerOfMass", centerOfMass, true },
	[5] = { "percentSubmerged", percentSubmerged },
	[6] = { "tractionMultiplier", tractionMultiplier },
	[7] = { "tractionLoss", tractionLoss },
	[8] = { "tractionBias", tractionBias },
	[9] = { "numberOfGears", numberOfGears },
	[10] = { "maxVelocity", maxVelocity },
	[11] = { "engineAcceleration", engineAcceleration },
	[12] = { "engineInertia", engineInertia },
	[13] = { "driveType", driveType, false, true },
	[14] = { "engineType", engineType, false, true },
	[14] = { "engineType", engineType, false, true },
	[15] = { "brakeDeceleration", brakeDeceleration },
	[16] = { "brakeBias", brakeBias },
	[17] = { "ABS", ABS },
	[18] = { "steeringLock", steeringLock },
	[19] = { "suspensionForceLevel", suspensionForceLevel },
	[20] = { "suspensionDamping", suspensionDamping },
	[21] = { "suspensionHighSpeedDamping", suspensionHighSpeedDamping },
	[22] = { "suspensionUpperLimit", suspensionUpperLimit },
	[23] = { "suspensionLowerLimit", suspensionLowerLimit },
	[24] = { "suspensionFrontRearBias", suspensionFrontRearBias },
	[25] = { "suspensionAntiDiveMultiplier", suspensionAntiDiveMultiplier },
	[26] = { "seatOffsetDistance", seatOffsetDistance },
	[27] = { "collisionDamageMultiplier", collisionDamageMultiplier },
	[28] = { "monetary", monetary },
	[29] = { "modelFlags", modelFlags },
	[30] = { "handlingFlags", handlingFlags },
	[31] = { "headLight", headLight, false, true },
	[32] = { "tailLight", tailLight, false, true },
	[33] = { "animGroup", animGroup },
}
